### PR TITLE
Format source .Rmd files to be at most 80 characters long

### PR DESCRIPTION
**Pull request by lorenzwalthert**
One thing: Was actually not sure whether or not to put a space after the last word on a line (not for code, but for plain english sentences). Can you @hadley advise on that and maybe we can add this to section 2.5 if you consider this to matter at all?
Nothing apart from the line breaks in the .Rmd files was changed which can be *proofed* by building the book (which I did) and noting that no other files tracked by git were modified.

### CODE REVIEW

**Comment by hadley** [comment]
I wouldn't usually add trailing whitespaces, but I don't think it's important (or common) enough to mention explicitly.

**Comment by lorenzwalthert** [comment]
Ok, should I remove those trailing spaces then?

**Comment by hadley** [comment]
I don't really care either way

**Comment by lorenzwalthert** [comment]
Ok, then I won't change it anymore. Anything else I should do before this is ready for merging?

**Comment by hadley** [comment]
No 😉

**Pull request merged**
