### PR TITLE
Only add full stop if there are more than one sentence in error messages

### PR DESCRIPTION
**Pull request by lionel-**
This style is more consistent with the standard style for commit messages and comments, and looks more fluid in the one-sentence case.

Also mentions that bulleted points should end with a full stop if they are a sentence or if they complete a sentence, following the advice in https://www.businesswritingblog.com/business_writing/2012/01/punctuating-bullet-points-.html

### CODE REVIEW

**Comment by hadley** [comment]
Changing this across the tidyverse would be a lot of work, and I'm not sure it's a clear win. I like all errors ending with a full stop because it makes it more clear they're a sentence, not a heading.

**Comment by lionel-** [comment]
My sense is that a majority of error messages in r-lib/tidyverse do not end with a full stop. I think we forget to add it because it feels more natural to read and write, as we are used to write this punctuation in code comments and commit messages, and to read it in shell, python, base R errors etc.

One advantage of always using a full stop is that it is more consistent when extra information is appended to the message, such as the `last_error()` reminder.

**Comment by hadley** [comment]
@krlmlr what do you think?

**Comment by krlmlr** [comment]
Not sure. The full stop does soften the message a bit, IMO, and it's also easier to append further sentences to it (as Lionel mentioned). The "always full stop" rule seems easier from a purely practical standpoint, too.

**Comment by lionel-** [comment]
I agree it's easier if all sentences end with a full stop.

**Pull request closed without merging**
