### PR TITLE
Do not put spaces inside the `{{` operator.

### LINKED ISSUE #139: Add spacing for `{{ var }}` (embracing) style
Not sure if this is settled yet, but once it is, we should add this to 
https://github.com/tidyverse/style/blob/a3bb5227e930c89e427dc379169a775b73e7a65e/syntax.Rmd#L53

### PR DESCRIPTION
**Pull request by gvwilson**
Closes #139.

### CODE REVIEW

**Comment by hadley** [comment]
I think our convention _is_ to put spaces.

**Comment by gvwilson** [comment]
cc @batpigandme - the example in https://www.tidyverse.org/articles/2019/06/rlang-0-4-0/ has the spaces, but following up the Slack discussion thread, this is inconsistent with how we treat `(...)` and `[...]`. If the call is to include spaces, I'll amend the PR and point out the difference.

**Comment by lionel-** [comment]
FWIW, I still think using spaces is the preferred style. From Slack:

> Oh did you mean the groupings outside {{ Jim? Then I agree, but it's part of the point, I think. When you look at the function from far away (look at its type color, in typographical terms), the other syntactical units are less prominent and you sort of see holes in the function where {{ was used. I think that makes it easy to see at a first glance (a) which arguments of the function are quoted, and (b) what are the varying parts in the code.
>
> That said, the style I initially chosen for !! and !!! had too much spacing, and was eventually changed. So please don't take the introductory blog post as the definite truth about how to style {{.

**Comment by lorenzwalthert** [comment]
I plan to release styler v1.2 soon, mainly because of styling around curly-curly, because the current CRAN release formats it like this: 

``` r
styler::style_text("call({{ x }})")
#> call({
#>   {
#>     x
#>   }
#> })
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And this is really unpleasing and may make people turn away from styler. I implemented spacing in https://github.com/r-lib/styler/pull/528 to the best of my knowledge as `{{ x }}`. If consensus on that should change, I'd (unhapply) adopt to another way of formatting it.

**Pull request closed without merging**
