### PR TITLE
Brace symmetry and spaces around ^

### PR DESCRIPTION
**Pull request by krlmlr**
Reference: https://github.com/r-lib/styler/issues/254#issuecomment-340277627

CC @lorenzwalthert.

@hadley: Some function calls with blocks aren't formatted correctly in styler, it would help if we could formalize the rules here. Do we need more examples?

### CODE REVIEW

**Comment by hadley** [comment]
I feel like there's probably a better way to formalise this rule, but I can't see how to express it clearly. It's more like matching (symmetrically) the pattern of the opening braces.

**Comment by krlmlr** [comment]
I have also edited the part where operator spacing is discussed, following https://github.com/tidyverse/dplyr/pull/3261/files#r158605017. CC @lionel- @lorenzwalthert @batpigandme.

**Comment by lorenzwalthert** [comment]
@krlmlr do we need to adapt styler defaults for math token spacing? Also, maybe we can explicitly add / and * in the examples above just to be explicit. Should there be a space around them or not?

**Comment by krlmlr** [comment]
@lorenzwalthert: There is an example for `/` and an explicit suggestion to use parentheses if in doubt, feels sufficient to me. Working on updating styler.

**Comment by lorenzwalthert** [comment]
Ok, I meant in turn floating text enumeration. But probably you are right and it's sufficient.

**Pull request merged**
