### PR TITLE
Changes from rpkgs plus cosmetic changes

### PR DESCRIPTION
**Pull request by lorenzwalthert**
* Incorporate changes from r-pkgs from issue #18. 
* Remove random text as discovered [here](https://github.com/tidyverse/style/commit/d7b4655eeb115ec00c9de1219033758296863c41#diff-0a5a223339888d0dc5ffe3b86d878aa5L28).
* Apply style rule to not exceed 80 characters per line to whole book.

### CODE REVIEW

**Comment by hadley** [comment]
Can you remove da140a5? We need to discuss it, and it makes it hard to review the other changes because of all the whitespace diffs.

**Comment by lorenzwalthert** [comment]
Sure. I can do a separate PR for this afterwards.

**Comment by lorenzwalthert** [comment]
Ok, this is ready for reviewing.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
